# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

exclude = "^tests/json-canonicalization/"

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v5.0.0"

[[repos.hooks]]
id = "trailing-whitespace"
groups = ["watch", "commit"]

[[repos.hooks]]
id = "end-of-file-fixer"
groups = ["watch", "commit"]

[[repos.hooks]]
id = "check-toml"
groups = ["commit"]

[[repos.hooks]]
id = "check-yaml"
groups = ["commit"]

[[repos.hooks]]
id = "check-merge-conflict"
groups = ["commit"]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.13.3"

[[repos.hooks]]
id = "ruff-check"
args = ["--fix"]
groups = ["watch", "commit"]

[[repos.hooks]]
id = "ruff-format"
groups = ["watch", "commit"]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "basedpyright"
name = "basedpyright"
entry = "uv run basedpyright"
language = "system"
types = ["python"]
pass_filenames = false
groups = ["commit"]

[[repos.hooks]]
id = "mypy"
name = "mypy"
entry = "uv run mypy"
language = "system"
types = ["python"]
pass_filenames = false
groups = ["commit"]

[[repos.hooks]]
id = "taplo"

name = "taplo fmt"
entry = "uv run taplo fmt"
language = "system"
types = ["toml"]
groups = ["watch", "commit"]
